import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Phone, MapPin, Building2, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
export default function ContactPage() {
    return (_jsxs("div", { className: "bg-slate-50 min-h-screen", children: [_jsxs("div", { className: "bg-[#0d2c54] py-20 text-center text-white", children: [_jsx("h1", { className: "text-4xl font-black mb-2 uppercase italic tracking-tighter", children: "Get in Touch" }), _jsx("p", { className: "opacity-70 text-sm", children: "We are here to assist you with your logistics needs." })] }), _jsx("div", { className: "container mx-auto px-4 -mt-10 pb-20", children: _jsxs("div", { className: "grid lg:grid-cols-2 gap-8", children: [_jsxs("div", { className: "bg-white p-8 md:p-12 rounded-3xl shadow-xl border", children: [_jsx("h3", { className: "text-2xl font-black text-[#0d2c54] mb-8 uppercase tracking-tighter", children: "Send us a Message" }), _jsxs("form", { className: "space-y-6", children: [_jsxs("div", { className: "grid md:grid-cols-2 gap-4", children: [_jsx(Input, { placeholder: "Your Name", className: "h-12 border-2" }), _jsx(Input, { placeholder: "Phone Number", className: "h-12 border-2" })] }), _jsx(Input, { placeholder: "Subject", className: "h-12 border-2" }), _jsx(Textarea, { placeholder: "How can we help you?", className: "min-h-[150px] border-2" }), _jsxs(Button, { className: "w-full h-14 bg-[#ff6b00] hover:bg-[#e66000] text-white font-black uppercase tracking-widest", children: ["Send Message ", _jsx(Send, { className: "ml-2", size: 18 })] })] })] }), _jsxs("div", { className: "space-y-6", children: [_jsx("h3", { className: "text-2xl font-black text-[#0d2c54] mb-8 uppercase tracking-tighter", children: "Our Locations" }), _jsx(BranchCard, { icon: _jsx(Building2, {}), title: "Yangon Head Office", addr: "No. 277, Corner of Anawrahta Road and Bo Moe Gyo St., East Dagon Township.", phone: "09-897447744" }), _jsx(BranchCard, { icon: _jsx(MapPin, {}), title: "Mandalay Hub", addr: "Serving Upper Myanmar Region.", phone: "09-422299994" })] })] }) })] }));
}
const BranchCard = ({ icon, title, addr, phone }) => (_jsxs("div", { className: "flex items-start gap-4 bg-white p-6 rounded-2xl border border-l-8 border-l-[#0d2c54] shadow-sm", children: [_jsx("div", { className: "text-[#ff6b00] mt-1", children: icon }), _jsxs("div", { children: [_jsx("h6", { className: "font-black text-[#0d2c54] uppercase text-sm mb-1", children: title }), _jsx("p", { className: "text-xs text-slate-500 mb-2 leading-relaxed", children: addr }), _jsxs("p", { className: "text-sm font-bold text-blue-700 flex items-center gap-1", children: [_jsx(Phone, { size: 14 }), " ", phone] })] })] }));
