import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { DollarSign, TrendingUp, CreditCard, Wallet } from 'lucide-react';
export default function Finance() {
    const stats = [
        { label: 'Total Revenue', value: '$125,000', icon: DollarSign, trend: '+12%' },
        { label: 'COD Collected', value: '$45,000', icon: Wallet, trend: '+8%' },
        { label: 'Outstanding AR', value: '$23,000', icon: CreditCard, trend: '-5%' },
        { label: 'Monthly Growth', value: '15.2%', icon: TrendingUp, trend: '+3%' }
    ];
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold tracking-tight", children: "Finance" }), _jsx("p", { className: "text-muted-foreground", children: "Financial overview and management" })] }), _jsx("div", { className: "grid gap-4 md:grid-cols-2 lg:grid-cols-4", children: stats.map((stat, index) => (_jsxs(Card, { className: "card-modern", children: [_jsxs(CardHeader, { className: "flex flex-row items-center justify-between space-y-0 pb-2", children: [_jsx(CardTitle, { className: "text-sm font-medium", children: stat.label }), _jsx(stat.icon, { className: "h-4 w-4 text-muted-foreground" })] }), _jsxs(CardContent, { children: [_jsx("div", { className: "text-2xl font-bold", children: stat.value }), _jsxs("p", { className: "text-xs text-muted-foreground", children: [_jsx("span", { className: "text-success", children: stat.trend }), " from last month"] })] })] }, index))) }), _jsxs(Card, { className: "card-modern", children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Recent Transactions" }) }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium", children: "COD Collection - EDS001" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Today, 2:30 PM" })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "font-medium", children: "$150.00" }), _jsx("p", { className: "text-sm text-success", children: "Completed" })] })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium", children: "COD Collection - EDS002" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Today, 1:15 PM" })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "font-medium", children: "$75.50" }), _jsx("p", { className: "text-sm text-success", children: "Completed" })] })] })] }) })] })] }));
}
