import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Building2, Package, QrCode, Truck, ArrowRight, Clock } from 'lucide-react';
export default function HubOperations() {
    const mockInboundPackages = [
        { awb: 'HUB123456789', origin: 'Mumbai Hub', destination: 'Delhi Hub', status: 'arrived' },
        { awb: 'HUB987654321', origin: 'Chennai Hub', destination: 'Bangalore Hub', status: 'sorting' },
        { awb: 'HUB456789123', origin: 'Kolkata Hub', destination: 'Hyderabad Hub', status: 'pending' }
    ];
    const mockOutboundBags = [
        { bagId: 'BAG001', destination: 'Delhi Hub', packages: 25, status: 'sealed' },
        { bagId: 'BAG002', destination: 'Mumbai Hub', packages: 18, status: 'packing' },
        { bagId: 'BAG003', destination: 'Chennai Hub', packages: 32, status: 'ready' }
    ];
    return (_jsxs("div", { className: "container mx-auto p-4 space-y-6", children: [_jsxs("div", { className: "text-center space-y-2", children: [_jsxs("h1", { className: "text-2xl font-bold flex items-center justify-center gap-2", children: [_jsx(Building2, { className: "h-6 w-6" }), "Hub Operations Center"] }), _jsx("p", { className: "text-muted-foreground", children: "Inbound scanning and sorting operations" })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4", children: [_jsx(Card, { children: _jsxs(CardContent, { className: "p-4 text-center", children: [_jsx(Package, { className: "h-8 w-8 mx-auto mb-2 text-blue-600" }), _jsx("p", { className: "text-2xl font-bold", children: "156" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Inbound Today" })] }) }), _jsx(Card, { children: _jsxs(CardContent, { className: "p-4 text-center", children: [_jsx(QrCode, { className: "h-8 w-8 mx-auto mb-2 text-green-600" }), _jsx("p", { className: "text-2xl font-bold", children: "142" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Scanned" })] }) }), _jsx(Card, { children: _jsxs(CardContent, { className: "p-4 text-center", children: [_jsx(Truck, { className: "h-8 w-8 mx-auto mb-2 text-orange-600" }), _jsx("p", { className: "text-2xl font-bold", children: "8" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Bags Sealed" })] }) }), _jsx(Card, { children: _jsxs(CardContent, { className: "p-4 text-center", children: [_jsx(Clock, { className: "h-8 w-8 mx-auto mb-2 text-purple-600" }), _jsx("p", { className: "text-2xl font-bold", children: "14" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Pending Sort" })] }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(Package, { className: "h-5 w-5" }), "Inbound Packages"] }) }), _jsx(CardContent, { className: "space-y-3", children: mockInboundPackages.map((pkg) => (_jsxs("div", { className: "flex items-center justify-between p-3 border rounded-lg", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(QrCode, { className: "h-5 w-5 text-muted-foreground" }), _jsxs("div", { children: [_jsx("p", { className: "font-mono font-medium", children: pkg.awb }), _jsxs("p", { className: "text-sm text-muted-foreground", children: [pkg.origin, " ", _jsx(ArrowRight, { className: "h-3 w-3 inline mx-1" }), " ", pkg.destination] })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: pkg.status === 'arrived' ? 'default' :
                                                pkg.status === 'sorting' ? 'secondary' : 'outline', children: pkg.status }), _jsxs(Button, { size: "sm", children: [_jsx(QrCode, { className: "h-4 w-4 mr-2" }), "Scan"] })] })] }, pkg.awb))) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(Truck, { className: "h-5 w-5" }), "Outbound Bags"] }) }), _jsx(CardContent, { className: "space-y-3", children: mockOutboundBags.map((bag) => (_jsxs("div", { className: "flex items-center justify-between p-3 border rounded-lg", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Package, { className: "h-5 w-5 text-muted-foreground" }), _jsxs("div", { children: [_jsx("p", { className: "font-medium", children: bag.bagId }), _jsxs("p", { className: "text-sm text-muted-foreground", children: ["To: ", bag.destination, " \u2022 ", bag.packages, " packages"] })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: bag.status === 'sealed' ? 'default' :
                                                bag.status === 'ready' ? 'secondary' : 'outline', children: bag.status }), _jsx(Button, { size: "sm", variant: "outline", children: bag.status === 'sealed' ? 'Dispatch' : 'Seal Bag' })] })] }, bag.bagId))) })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4", children: [_jsx(Button, { variant: "outline", className: "h-20", children: _jsxs("div", { className: "text-center", children: [_jsx(QrCode, { className: "h-6 w-6 mx-auto mb-2" }), _jsx("p", { className: "text-sm", children: "Bulk Inbound Scan" })] }) }), _jsx(Button, { variant: "outline", className: "h-20", children: _jsxs("div", { className: "text-center", children: [_jsx(Package, { className: "h-6 w-6 mx-auto mb-2" }), _jsx("p", { className: "text-sm", children: "Sort Packages" })] }) }), _jsx(Button, { variant: "outline", className: "h-20", children: _jsxs("div", { className: "text-center", children: [_jsx(Truck, { className: "h-6 w-6 mx-auto mb-2" }), _jsx("p", { className: "text-sm", children: "Create Bag" })] }) }), _jsx(Button, { variant: "outline", className: "h-20", children: _jsxs("div", { className: "text-center", children: [_jsx(Building2, { className: "h-6 w-6 mx-auto mb-2" }), _jsx("p", { className: "text-sm", children: "Hub Reports" })] }) })] })] }));
}
