import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Calendar, User, ArrowRight } from 'lucide-react';
export default function NewsPage() {
    const posts = [
        { title: "Expanding our Mandalay Hub", date: "2026-02-20", excerpt: "New facilities to serve Upper Myanmar faster." },
        { title: "International Shipping Rates Update", date: "2026-02-15", excerpt: "New competitive rates for USA and UK air cargo." }
    ];
    return (_jsxs("div", { className: "bg-slate-50 min-h-screen pb-20", children: [_jsxs("div", { className: "bg-[#0d2c54] py-20 text-center text-white", children: [_jsx("h1", { className: "text-4xl font-black mb-2 uppercase tracking-tighter", children: "News & Updates" }), _jsx("p", { className: "opacity-70 text-sm", children: "Stay informed with Britium Express." })] }), _jsx("div", { className: "container mx-auto px-4 mt-12", children: _jsx("div", { className: "grid md:grid-cols-2 lg:grid-cols-3 gap-8", children: posts.map((post, i) => (_jsxs("div", { className: "bg-white rounded-3xl shadow-lg overflow-hidden border transition-transform hover:-translate-y-2", children: [_jsx("div", { className: "h-48 bg-slate-200" }), _jsxs("div", { className: "p-8", children: [_jsxs("div", { className: "flex items-center gap-4 text-[10px] font-bold text-slate-400 uppercase mb-4", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Calendar, { size: 12 }), " ", post.date] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(User, { size: 12 }), " Admin"] })] }), _jsx("h3", { className: "text-xl font-black text-[#0d2c54] mb-4 uppercase tracking-tighter leading-tight", children: post.title }), _jsx("p", { className: "text-sm text-slate-500 mb-6", children: post.excerpt }), _jsxs("button", { className: "text-[#ff6b00] font-black text-xs uppercase flex items-center gap-1 hover:gap-2 transition-all", children: ["Read More ", _jsx(ArrowRight, { size: 14 })] })] })] }, i))) }) })] }));
}
