import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Package } from 'lucide-react';
import { Button } from '@/components/ui/button';
export default function Quote() {
    const [form, setForm] = useState({ townshipRate: 0, weight: 1 });
    const calculateTotal = () => {
        if (form.townshipRate === 0)
            return 0;
        // Base rate for 1st Kg + 500 MMK per additional Kg
        const extraWeightCost = form.weight > 1 ? (form.weight - 1) * 500 : 0;
        return form.townshipRate + extraWeightCost;
    };
    return (_jsx("div", { className: "py-16 bg-slate-50 min-h-screen", children: _jsxs("div", { className: "container mx-auto px-4 max-w-4xl", children: [_jsx("h2", { className: "text-3xl font-black text-[#0d2c54] mb-8 uppercase italic tracking-tighter", children: "Shipping Rate Calculator" }), _jsxs("div", { className: "grid md:grid-cols-5 gap-0 bg-white rounded-3xl shadow-2xl overflow-hidden border", children: [_jsxs("div", { className: "md:col-span-3 p-8 md:p-12", children: [_jsxs("h4", { className: "text-xs font-black text-slate-400 uppercase tracking-widest mb-8 flex items-center gap-2", children: [_jsx(Package, { size: 14, className: "text-[#ff6b00]" }), " Shipment Details"] }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-bold mb-2", children: "Yangon Destination Township" }), _jsxs("select", { className: "w-full h-12 rounded-xl border-2 px-4 bg-slate-50 font-medium", onChange: (e) => setForm({ ...form, townshipRate: parseInt(e.target.value) }), children: [_jsx("option", { value: "0", children: "-- Select Area --" }), _jsx("optgroup", { label: "Zone 1 - 3,000 MMK", children: _jsx("option", { value: "3000", children: "Bahan / Sanchaung / Kamaryut" }) }), _jsx("optgroup", { label: "Zone 2 - 3,500 MMK", children: _jsx("option", { value: "3500", children: "East Dagon / North Dagon / South Dagon" }) })] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-bold mb-2", children: "Estimated Weight (Kg)" }), _jsx("input", { type: "number", min: "1", value: form.weight, onChange: (e) => setForm({ ...form, weight: parseFloat(e.target.value) }), className: "w-full h-12 rounded-xl border-2 px-4 bg-slate-50" })] })] })] }), _jsxs("div", { className: "md:col-span-2 bg-slate-900 p-12 text-center flex flex-col justify-center border-l border-slate-800", children: [_jsx("span", { className: "text-[10px] font-black text-slate-500 uppercase tracking-[0.2em] mb-2", children: "Estimated Total" }), _jsxs("h3", { className: "text-4xl font-black text-[#ff6b00] mb-8", children: [calculateTotal().toLocaleString(), " ", _jsx("span", { className: "text-xs text-white", children: "MMK" })] }), _jsx(Button, { className: "w-full h-14 bg-[#ff6b00] hover:bg-[#e66000] text-white font-black text-sm uppercase tracking-widest rounded-xl", children: "Book Shipment" }), _jsx("p", { className: "text-[10px] text-slate-500 italic mt-6", children: "*Price includes base rate and additional weight surcharge." })] })] })] }) }));
}
