import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Truck, CircleDollarSign, Plane, Calculator } from 'lucide-react';
export default function ServicesPage() {
  const { t } = useLanguageContext();
  const { t } = useLanguageContext();
  const { t } = useLanguageContext();
    const [calcData, setCalcData] = useState({ dest: 0, weight: 0, l: 0, w: 0, h: 0, divisor: 5000 });
    const [result, setResult] = useState(null);
    const calculate = (e) => {
        e.preventDefault();
        const volWeight = (calcData.l * calcData.w * calcData.h) / calcData.divisor;
        const chargeable = Math.max(calcData.weight, volWeight);
        setResult(chargeable * calcData.dest); //
    };
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsxs("div", { className: "bg-[#0d2c54] py-20 text-center text-white px-4", children: [_jsx("h1", { className: "text-4xl md:text-5xl font-extrabold mb-4", children: "Our Logistics Solutions" }), _jsx("p", { className: "max-w-2xl mx-auto text-lg opacity-80", children: "From domestic parcels to international air cargo." })] }), _jsx("section", { className: "container mx-auto py-16 px-4", children: _jsxs("div", { className: "grid md:grid-cols-3 gap-8", children: [_jsx(ServiceCard, { img: "https://images.unsplash.com/photo-1580674285054-bed31e145f59", icon: _jsx(Truck, {}), title: "Domestic Express", desc: "Door-to-door delivery connecting Yangon, Mandalay, and Nay Pyi Taw.", link: "/domestic" }), _jsx(ServiceCard, { img: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1", icon: _jsx(CircleDollarSign, {}), title: "COD & E-Commerce", desc: "Grow your online shop with secure payments and 24-hour remittance.", link: "/ecommerce" }), _jsx(ServiceCard, { img: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05", icon: _jsx(Plane, {}), title: "International Cargo", desc: "Reliable air freight forwarding to USA, Singapore, Thailand, and Europe.", link: "/quote" })] }) }), _jsx("section", { className: "bg-white py-16 border-y", children: _jsx("div", { className: "container mx-auto px-4 max-w-4xl", children: _jsxs("div", { className: "bg-white p-8 rounded-2xl shadow-xl border-t-8 border-[#0d2c54]", children: [_jsx("h2", { className: "text-2xl font-bold mb-6 text-center", children: "International Air Cargo Calculator" }), _jsx("form", { onSubmit: calculate, className: "grid md:grid-cols-2 gap-6", children: _jsxs(Button, { type: "submit", className: "md:col-span-2 bg-[#ff6b00] hover:bg-[#e66000] text-white py-6 text-lg font-bold", children: [_jsx(Calculator, { className: "mr-2" }), " Calculate Estimate"] }) }), result !== null && (_jsxs("div", { className: "mt-8 p-6 bg-blue-50 border-2 border-dashed border-[#0d2c54] rounded-lg text-center", children: [_jsx("p", { className: "text-gray-600 uppercase text-xs font-bold", children: "Estimated Cost" }), _jsxs("h2", { className: "text-4xl font-black text-[#0d2c54]", children: ["$", result.toFixed(2)] })] }))] }) }) })] }));
}
const ServiceCard = ({ img, icon, title, desc, link }) => (_jsxs("div", { className: "bg-white rounded-xl shadow-lg overflow-hidden transition-transform hover:-translate-y-2 group", children: [_jsx("img", { src: img, className: "h-56 w-full object-cover", alt: title }), _jsxs("div", { className: "p-8 text-center relative", children: [_jsx("div", { className: "w-16 h-16 bg-[#ff6b00] text-white rounded-full flex items-center justify-center mx-auto -mt-16 mb-6 border-4 border-white shadow-lg", children: icon }), _jsx("h4", { className: "text-xl font-bold mb-3", children: title }), _jsx("p", { className: "text-gray-500 text-sm mb-6", children: desc }), _jsx(Link, { to: link, className: "text-[#0d2c54] font-bold hover:underline", children: "View More \u2192" })] })] }));
