import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, AreaChart, Area, PieChart, Pie, Cell, Legend, } from 'recharts';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
const CustomTooltip = ({ active, payload, label, valuePrefix = '' }) => {
    if (active && payload && payload.length) {
        return (_jsxs("div", { className: "bg-card border border-border p-3 rounded-lg shadow-lg backdrop-blur-md", children: [_jsx("p", { className: "text-xs font-semibold text-muted-foreground mb-1", children: label }), payload.map((entry, index) => (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-2 h-2 rounded-full", style: { backgroundColor: entry.color } }), _jsxs("p", { className: "text-sm font-mono font-medium", children: [entry.name, ": ", valuePrefix, entry.value.toLocaleString()] })] }, index)))] }));
    }
    return null;
};
export function DeliveryChart({ data }) {
    return (_jsxs(Card, { className: "w-full h-full min-h-[400px] border-none shadow-none bg-transparent", children: [_jsxs(CardHeader, { className: "px-0", children: [_jsx(CardTitle, { className: "text-lg font-semibold", children: "Delivery Volume" }), _jsx(CardDescription, { children: "Daily shipment throughput and completion rate" })] }), _jsx(CardContent, { className: "p-0 h-[300px]", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(AreaChart, { data: data, margin: { top: 10, right: 10, left: 0, bottom: 0 }, children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "colorTotal", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "var(--primary)", stopOpacity: 0.3 }), _jsx("stop", { offset: "95%", stopColor: "var(--primary)", stopOpacity: 0 })] }), _jsxs("linearGradient", { id: "colorDelivered", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "var(--accent)", stopOpacity: 0.3 }), _jsx("stop", { offset: "95%", stopColor: "var(--accent)", stopOpacity: 0 })] })] }), _jsx(CartesianGrid, { strokeDasharray: "3 3", vertical: false, stroke: "var(--border)" }), _jsx(XAxis, { dataKey: "name", axisLine: false, tickLine: false, tick: { fill: 'var(--muted-foreground)', fontSize: 12 }, dy: 10 }), _jsx(YAxis, { axisLine: false, tickLine: false, tick: { fill: 'var(--muted-foreground)', fontSize: 12 } }), _jsx(Tooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(Area, { type: "monotone", dataKey: "total", stroke: "var(--primary)", strokeWidth: 2, fillOpacity: 1, fill: "url(#colorTotal)", name: "Total Shipments" }), _jsx(Area, { type: "monotone", dataKey: "delivered", stroke: "var(--accent)", strokeWidth: 2, fillOpacity: 1, fill: "url(#colorDelivered)", name: "Delivered" })] }) }) })] }));
}
export function RevenueChart({ data }) {
    return (_jsxs(Card, { className: "w-full h-full min-h-[400px] border-none shadow-none bg-transparent", children: [_jsxs(CardHeader, { className: "px-0", children: [_jsx(CardTitle, { className: "text-lg font-semibold", children: "Financial Overview" }), _jsx(CardDescription, { children: "Revenue vs. Operational Expenses (USD)" })] }), _jsx(CardContent, { className: "p-0 h-[300px]", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(LineChart, { data: data, margin: { top: 10, right: 10, left: 0, bottom: 0 }, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", vertical: false, stroke: "var(--border)" }), _jsx(XAxis, { dataKey: "month", axisLine: false, tickLine: false, tick: { fill: 'var(--muted-foreground)', fontSize: 12 }, dy: 10 }), _jsx(YAxis, { axisLine: false, tickLine: false, tick: { fill: 'var(--muted-foreground)', fontSize: 12 }, tickFormatter: (value) => `$${value / 1000}k` }), _jsx(Tooltip, { content: _jsx(CustomTooltip, { valuePrefix: "$" }) }), _jsx(Legend, { verticalAlign: "top", align: "right", iconType: "circle", wrapperStyle: { paddingBottom: '20px', fontSize: '12px' } }), _jsx(Line, { type: "stepAfter", dataKey: "revenue", stroke: "var(--primary)", strokeWidth: 3, dot: { r: 4, fill: 'var(--primary)', strokeWidth: 2, stroke: 'var(--card)' }, activeDot: { r: 6 }, name: "Revenue" }), _jsx(Line, { type: "monotone", dataKey: "expense", stroke: "var(--destructive)", strokeWidth: 2, strokeDasharray: "5 5", dot: false, name: "Expenses" })] }) }) })] }));
}
export function PerformanceChart({ data }) {
    const COLORS = [
        'oklch(0.60 0.16 150)', // Success/Delivered
        'oklch(0.48 0.16 255)', // Primary/Pending
        'oklch(0.72 0.18 45)', // Accent/In Transit
        'oklch(0.60 0.20 25)', // Destructive/Failed
    ];
    return (_jsxs(Card, { className: "w-full h-full min-h-[400px] border-none shadow-none bg-transparent", children: [_jsxs(CardHeader, { className: "px-0", children: [_jsx(CardTitle, { className: "text-lg font-semibold", children: "Fleet Performance" }), _jsx(CardDescription, { children: "Status distribution across active shipments" })] }), _jsx(CardContent, { className: "p-0 h-[300px] flex items-center justify-center", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(PieChart, { children: [_jsx(Pie, { data: data, cx: "50%", cy: "50%", innerRadius: 60, outerRadius: 100, paddingAngle: 5, dataKey: "value", nameKey: "name", children: data.map((_, index) => (_jsx(Cell, { fill: COLORS[index % COLORS.length], stroke: "transparent" }, `cell-${index}`))) }), _jsx(Tooltip, { contentStyle: { backgroundColor: 'var(--card)', border: '1px solid var(--border)', borderRadius: '8px' }, itemStyle: { color: 'var(--foreground)', fontFamily: 'var(--font-mono)' } }), _jsx(Legend, { verticalAlign: "bottom", align: "center", layout: "horizontal", iconType: "circle", wrapperStyle: { fontSize: '12px', paddingTop: '20px' } })] }) }) })] }));
}
