import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { NavLink, Link } from 'react-router-dom';
import { LayoutDashboard, Package, Truck, Warehouse as WarehouseIcon, MapPin, BarChart3, Settings, Menu, X, Users, CreditCard, QrCode, Zap, Calculator, Briefcase } from 'lucide-react';
import { ROUTE_PATHS } from '@/lib/index';
const navigationItems = [
    { label: 'Dashboard', href: ROUTE_PATHS.DASHBOARD, icon: LayoutDashboard },
    { label: 'Operations', href: ROUTE_PATHS.OPERATIONS, icon: Briefcase },
    { label: 'Shipments', href: ROUTE_PATHS.SHIPMENTS, icon: Package },
    { label: 'Fleet', href: ROUTE_PATHS.FLEET, icon: Truck },
    { label: 'Warehouse', href: ROUTE_PATHS.WAREHOUSE, icon: WarehouseIcon },
    { label: 'Delivery', href: ROUTE_PATHS.DELIVERY, icon: MapPin },
    { label: 'Analytics', href: ROUTE_PATHS.ANALYTICS, icon: BarChart3 },
    { label: 'Users', href: ROUTE_PATHS.USERS, icon: Users },
    { label: 'Finance', href: ROUTE_PATHS.FINANCE, icon: CreditCard },
    { label: 'Parcel Pickup', href: ROUTE_PATHS.PARCEL_PICKUP, icon: QrCode },
    { label: 'Advanced Logistics', href: ROUTE_PATHS.ADVANCED_LOGISTICS, icon: Zap },
    { label: 'Shipping Calculator', href: ROUTE_PATHS.SHIPPING_CALCULATOR, icon: Calculator },
    { label: 'Settings', href: ROUTE_PATHS.SETTINGS, icon: Settings },
];
export function SimpleLayout({ children }) {
    const [sidebarOpen, setSidebarOpen] = useState(false);
    return (_jsxs("div", { className: "flex h-screen bg-background", children: [_jsx("div", { className: "hidden lg:flex lg:w-64 lg:flex-col lg:fixed lg:inset-y-0", children: _jsxs("div", { className: "flex flex-col flex-grow bg-card border-r border-border overflow-y-auto", children: [_jsx("div", { className: "flex items-center flex-shrink-0 px-6 py-6", children: _jsxs(Link, { to: ROUTE_PATHS.DASHBOARD, className: "flex items-center space-x-3", children: [_jsx("div", { className: "h-10 w-10 bg-primary rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-primary-foreground font-bold text-lg", children: "B" }) }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-xl font-bold text-primary", children: "Britium Express" }), _jsx("span", { className: "text-xs text-muted-foreground", children: "Enterprise Logistics" })] })] }) }), _jsx("nav", { className: "flex-1 px-4 pb-4 space-y-1", children: navigationItems.map((item) => (_jsxs(NavLink, { to: item.href, className: ({ isActive }) => `group flex items-center px-3 py-2 text-sm font-medium rounded-lg transition-all duration-200 ${isActive
                                    ? 'bg-primary text-primary-foreground shadow-sm'
                                    : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'}`, children: [_jsx(item.icon, { className: "mr-3 h-5 w-5 flex-shrink-0" }), item.label] }, item.href))) })] }) }), sidebarOpen && (_jsx("div", { className: "fixed inset-0 z-40 bg-black bg-opacity-50 lg:hidden", onClick: () => setSidebarOpen(false) })), _jsx("div", { className: `fixed inset-y-0 left-0 z-50 w-64 bg-card border-r border-border transform transition-transform duration-300 lg:hidden ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}`, children: _jsxs("div", { className: "flex flex-col h-full", children: [_jsxs("div", { className: "flex items-center justify-between flex-shrink-0 px-6 py-6", children: [_jsxs(Link, { to: ROUTE_PATHS.DASHBOARD, className: "flex items-center space-x-3", children: [_jsx("div", { className: "h-8 w-8 bg-primary rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-primary-foreground font-bold", children: "B" }) }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-lg font-bold text-primary", children: "Britium Express" }), _jsx("span", { className: "text-xs text-muted-foreground", children: "Enterprise Logistics" })] })] }), _jsx("button", { onClick: () => setSidebarOpen(false), className: "p-2 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent", children: _jsx(X, { className: "h-5 w-5" }) })] }), _jsx("nav", { className: "flex-1 px-4 pb-4 space-y-1 overflow-y-auto", children: navigationItems.map((item) => (_jsxs(NavLink, { to: item.href, className: ({ isActive }) => `group flex items-center px-3 py-2 text-sm font-medium rounded-lg transition-all duration-200 ${isActive
                                    ? 'bg-primary text-primary-foreground shadow-sm'
                                    : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'}`, onClick: () => setSidebarOpen(false), children: [_jsx(item.icon, { className: "mr-3 h-5 w-5 flex-shrink-0" }), item.label] }, item.href))) })] }) }), _jsxs("div", { className: "flex flex-col flex-1 lg:pl-64", children: [_jsxs("header", { className: "flex items-center justify-between flex-shrink-0 px-6 py-4 bg-card border-b border-border", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("button", { onClick: () => setSidebarOpen(true), className: "p-2 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent lg:hidden", children: _jsx(Menu, { className: "h-5 w-5" }) }), _jsx("h1", { className: "text-lg font-semibold text-foreground", children: "Britium Express" })] }), _jsx("div", { className: "flex items-center space-x-4", children: _jsx("span", { className: "text-sm text-muted-foreground", children: "System Administrator" }) })] }), _jsx("main", { className: "flex-1 overflow-y-auto bg-background", children: _jsx("div", { className: "p-6", children: children }) })] })] }));
}
