import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import "bootstrap/dist/css/bootstrap.min.css";
import { FaPhoneAlt, FaEnvelope, FaClock, FaDoorOpen, FaBoxOpen, FaMobileAlt } from "react-icons/fa";
const DomesticExpress = () => {
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "bg-dark text-white py-2 small", children: _jsxs("div", { className: "container d-flex flex-column flex-md-row justify-content-between", children: [_jsxs("div", { children: [_jsx(FaPhoneAlt, { className: "me-2" }), " +95 9 897 4477 44", _jsxs("span", { className: "ms-3", children: [_jsx(FaEnvelope, { className: "me-2" }), " info@britiumexpress.com"] })] }), _jsxs("div", { children: [_jsx(FaClock, { className: "me-2" }), " Mon-Sat: 9:00am - 5:30pm"] })] }) }), _jsx("header", { className: "text-white text-center py-5", style: {
                    background: "linear-gradient(rgba(13,44,84,0.85), rgba(13,44,84,0.85)), url('https://images.unsplash.com/photo-1595150937666-419b48f93309')",
                    backgroundSize: "cover",
                }, children: _jsxs("div", { className: "container", children: [_jsx("h1", { className: "display-4 fw-bold", children: "Domestic Express" }), _jsx("p", { className: "lead", children: "Connecting Yangon, Mandalay, and Nay Pyi Taw with speed and precision." })] }) }), _jsx("section", { className: "py-5", children: _jsxs("div", { className: "container", children: [_jsx("h2", { className: "fw-bold mb-4 text-primary", children: "Priority Routes" }), _jsx(RouteCard, { title: "Yangon City Same-Day", subtitle: "Downtown & Major Townships", badge: "Same Day" }), _jsx(RouteCard, { title: "Yangon \u2192 Mandalay", subtitle: "Daily Highway Express", badge: "Next Day" }), _jsx(RouteCard, { title: "Yangon \u2192 Nay Pyi Taw", subtitle: "Government & Commercial Cargo", badge: "Next Day" })] }) }), _jsx("section", { className: "bg-light py-5 text-center", children: _jsxs("div", { className: "container row mx-auto", children: [_jsx(Feature, { icon: _jsx(FaDoorOpen, { size: 40 }), title: "Door-to-Door", text: "Pickup and deliver directly to receiver." }), _jsx(Feature, { icon: _jsx(FaBoxOpen, { size: 40 }), title: "Secure Handling", text: "Safe packaging and professional care." }), _jsx(Feature, { icon: _jsx(FaMobileAlt, { size: 40 }), title: "Real-Time Updates", text: "Track via Website or Mobile App." })] }) })] }));
};
const RouteCard = ({ title, subtitle, badge }) => (_jsx("div", { className: "card mb-3 shadow-sm border-start border-4 border-primary", children: _jsxs("div", { className: "card-body d-flex justify-content-between align-items-center", children: [_jsxs("div", { children: [_jsx("h5", { className: "fw-bold mb-1", children: title }), _jsx("small", { className: "text-muted", children: subtitle })] }), _jsx("span", { className: "badge bg-primary", children: badge })] }) }));
const Feature = ({ icon, title, text }) => (_jsxs("div", { className: "col-md-4", children: [_jsx("div", { className: "mb-3 text-warning", children: icon }), _jsx("h5", { className: "fw-bold", children: title }), _jsx("p", { className: "text-muted small", children: text })] }));
export default DomesticExpress;
